### ISSUE TITLE
Add test cases 

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/estimateGas-testing#2]
Please implement the following test cases.

Test case inputs:

* CONTRACT_ADDRESS
* TEST_TOKEN_ID (default = 1)
* You must authorize GIVER for the token in order to run the validator

Genius note:
 
* Create a helper contract called "giver" and deploy to all networks. One function give(). Requires 1000000 ether to run and it transfers a specified token on a specified contract to msg.sender.

# Test cases:

## Sanity checks

- [x] Find the amount of value (ether) assigned to CONTRACT_ADDRESS, it should be greater than or equal to zero 
- [x] Find the code_size of CONTRACT_ADDRESS, it should be greater than zero

## interface ERC721

- [x] Check interface 165
- [x] Check interface 721
- [x] Check interface ERC721Metadata
- [x] Check interface ERC721Enumerable

## interface ERC721

- [x] balanceOf(ownerOf(TEST_TOKEN_ID) should be > 0
- [x] balanceOf(0) should throw
- [x] ownerOf(TEST_TOKEN_ID) should return an address > 0
- [x] Choose three random tokenIds, run balanceOf(address) on each of them, none of these should return zero
- [x] Get token from giver (you must run this from an account, not necessarily one you own, that has 1000000 ether)
- [x] Get a token from giver, transferFrom self to a stub, check balanceOf() stub before and after transfer, it should be one more
- [x] Get a token from giver, transferFrom to zero address, should throw
- [x] transferFrom giver to self, this should throw because giver does not authorize the transaction
- [x] Get a token from giver, safe transfer to stub by sending data ffff. Stub throws in callback if it does not receive ffff
- [x] Get a token from giver, safe transfer to stub using the default argument. Stub throws in callback if it does not receive ""
- [x] Get a token from giver, safe transfer to stub by sending data ffff. Test fails if callback was not called
- [x] Get a token from giver, safe transfer to stub, the stub does not return the correct magic value, the transfer must throw
- [x] Get a token from giver, approve stub, then check getApproved stub
- [x] Get a token from giver, approve stub, then have stub transferFrom to stub2.
- [x] Get a token from giver, approveForAll to stub, then check isApprovedForAll
- [x] Get a token from giver, approveFor All to stub, then have stub transferFrom to stub2.

## interface ERC721Metadata

- [x] name() should not throw
- [x] symbol() should not throw
- [x] tokenURI(TEST_TOKEN_ID) should not throw

## interface ERC721Enumerable

- [x] totalSupply should be greater than 0
- [x] tokenByIndex(0) should not throw
- [x] Get token from giver, find balanceOf(self), tokenOfOwnerByIndex(0) should not throw
- [x] Get token from giver, find balanceOf(self), tokenOfOwnerByIndex(balanceOf(self)) should throw

# Notes

Read the 721 transfer rationale section. There are many failures that are allowed (see the bulleted list). Make sure we throw warnings, not errors for transfer functions if the transfer refuses to run for business reasons.

Imagine a test case "vampire contract". You don't need to write the contract, but imagine if your test cases would fail against it.

* Deploys with 2^256-1 tokens existing
* Each token owned by address = tokenId except for 0x0

**Comment by MoMannn** [comment]
This examples are all implemented here: https://github.com/0xcert/erc721-validator/blob/096d04b01dec172576743fe6131df1fb45f33f24/contracts/validator.sol

Since we will now be using this repo for article examples I believe that we should close the issues since their purpose was for building the https://erc721validator.org/ which lives in another repo.

**Comment by fulldecent** [comment]
Agree, thank you. Closing.
